In [58]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from datetime import datetime
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

In [2]:
data = pd.read_csv("fraudTrain.csv")

In [3]:
data

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296670,1296670,2020-06-21 12:12:08,30263540414123,fraud_Reichel Inc,entertainment,15.56,Erik,Patterson,M,162 Jessica Row Apt. 072,...,37.7175,-112.4777,258,Geoscientist,1961-11-24,440b587732da4dc1a6395aba5fb41669,1371816728,36.841266,-111.690765,0
1296671,1296671,2020-06-21 12:12:19,6011149206456997,fraud_Abernathy and Sons,food_dining,51.70,Jeffrey,White,M,8617 Holmes Terrace Suite 651,...,39.2667,-77.5101,100,"Production assistant, television",1979-12-11,278000d2e0d2277d1de2f890067dcc0a,1371816739,38.906881,-78.246528,0
1296672,1296672,2020-06-21 12:12:32,3514865930894695,fraud_Stiedemann Ltd,food_dining,105.93,Christopher,Castaneda,M,1632 Cohen Drive Suite 639,...,32.9396,-105.8189,899,Naval architect,1967-08-30,483f52fe67fabef353d552c1e662974c,1371816752,33.619513,-105.130529,0
1296673,1296673,2020-06-21 12:13:36,2720012583106919,"fraud_Reinger, Weissnat and Strosin",food_dining,74.90,Joseph,Murray,M,42933 Ryan Underpass,...,43.3526,-102.5411,1126,Volunteer coordinator,1980-08-18,d667cdcbadaaed3da3f4020e83591c83,1371816816,42.788940,-103.241160,0
1296674,1296674,2020-06-21 12:13:37,4292902571056973207,"fraud_Langosh, Wintheiser and Hyatt",food_dining,4.30,Jeffrey,Smith,M,135 Joseph Mountains,...,45.8433,-113.8748,218,"Therapist, horticultural",1995-08-16,8f7c8e4ab7f25875d753b422917c98c9,1371816817,46.565983,-114.186110,0

In [4]:
data.columns

Index(['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category',
       'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip',
       'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time',
       'merch_lat', 'merch_long', 'is_fraud'],
      dtype='object')

In [5]:
data = data.drop(["Unnamed: 0","trans_num","cc_num","first","last","street","lat","long","unix_time"],axis = 1)

In [6]:
data

,trans_date_trans_time,merchant,category,amt,gender,city,state,zip,city_pop,job,dob,merch_lat,merch_long,is_fraud
0,2019-01-01 00:00:18,"fraud_Rippin, Kub and Mann",misc_net,4.97,F,Moravian Falls,NC,28654,3495,"Psychologist, counselling",1988-03-09,36.011293,-82.048315,0
1,2019-01-01 00:00:44,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,F,Orient,WA,99160,149,Special educational needs teacher,1978-06-21,49.159047,-118.186462,0
2,2019-01-01 00:00:51,fraud_Lind-Buckridge,entertainment,220.11,M,Malad City,ID,83252,4154,Nature conservation officer,1962-01-19,43.150704,-112.154481,0
3,2019-01-01 00:01:16,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,M,Boulder,MT,59632,1939,Patent attorney,1967-01-12,47.034331,-112.561071,0
4,2019-01-01 00:03:06,fraud_Keeling-Crist,misc_pos,41.96,M,Doe Hill,VA,24433,99,Dance movement psychotherapist,1986-03-28,38.674999,-78.632459,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296670,2020-06-21 12:12:08,fraud_Reichel Inc,entertainment,15.56,M,Hatch,UT,84735,258,Geoscientist,1961-11-24,36.841266,-111.690765,0
1296671,2020-06-21 12:12:19,fraud_Abernathy and Sons,food_dining,51.70,M,Tuscarora,MD,21790,100,"Production assistant, television",1979-12-11,38.906881,-78.246528,0
1296672,2020-06-21 12:12:32,fraud_Stiedemann Ltd,food_dining,105.93,M,High Rolls Mountain Park,NM,88325,899,Naval architect,1967-08-30,33.619513,-105.130529,0
1296673,2020-06-21 12:13:36,"fraud_Reinger, Weissnat and Strosin",food_dining,74.90,M,Manderson,SD,57756,1126,Volunteer coordinator,1980-08-18,42.788940,-103.241160,0
1296674,2020-06-21 12:13:37,"fraud_Langosh, Wintheiser and Hyatt",food_dining,4.30,M,Sula,MT,59871,218,"Therapist, horticultural",1995-08-16,46.565983,-114.186110,0

In [7]:
encoder = LabelEncoder()
data["gender"] = encoder.fit_transform(data["gender"])

In [8]:
data

,trans_date_trans_time,merchant,category,amt,gender,city,state,zip,city_pop,job,dob,merch_lat,merch_long,is_fraud
0,2019-01-01 00:00:18,"fraud_Rippin, Kub and Mann",misc_net,4.97,0,Moravian Falls,NC,28654,3495,"Psychologist, counselling",1988-03-09,36.011293,-82.048315,0
1,2019-01-01 00:00:44,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,0,Orient,WA,99160,149,Special educational needs teacher,1978-06-21,49.159047,-118.186462,0
2,2019-01-01 00:00:51,fraud_Lind-Buckridge,entertainment,220.11,1,Malad City,ID,83252,4154,Nature conservation officer,1962-01-19,43.150704,-112.154481,0
3,2019-01-01 00:01:16,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,1,Boulder,MT,59632,1939,Patent attorney,1967-01-12,47.034331,-112.561071,0
4,2019-01-01 00:03:06,fraud_Keeling-Crist,misc_pos,41.96,1,Doe Hill,VA,24433,99,Dance movement psychotherapist,1986-03-28,38.674999,-78.632459,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296670,2020-06-21 12:12:08,fraud_Reichel Inc,entertainment,15.56,1,Hatch,UT,84735,258,Geoscientist,1961-11-24,36.841266,-111.690765,0
1296671,2020-06-21 12:12:19,fraud_Abernathy and Sons,food_dining,51.70,1,Tuscarora,MD,21790,100,"Production assistant, television",1979-12-11,38.906881,-78.246528,0
1296672,2020-06-21 12:12:32,fraud_Stiedemann Ltd,food_dining,105.93,1,High Rolls Mountain Park,NM,88325,899,Naval architect,1967-08-30,33.619513,-105.130529,0
1296673,2020-06-21 12:13:36,"fraud_Reinger, Weissnat and Strosin",food_dining,74.90,1,Manderson,SD,57756,1126,Volunteer coordinator,1980-08-18,42.788940,-103.241160,0
1296674,2020-06-21 12:13:37,"fraud_Langosh, Wintheiser and Hyatt",food_dining,4.30,1,Sula,MT,59871,218,"Therapist, horticultural",1995-08-16,46.565983,-114.186110,0

In [ ]:
category_encoder = OneHotEncoder()
encoded_category = category_encoder.fit_transform(data[["category"]]).toarray()
category_names = category_encoder.get_feature_names_out()
category_df = pd.DataFrame(encoded_category, columns=category_names)

In [11]:
category_df

,category_entertainment,category_food_dining,category_gas_transport,category_grocery_net,category_grocery_pos,category_health_fitness,category_home,category_kids_pets,category_misc_net,category_misc_pos,category_personal_care,category_shopping_net,category_shopping_pos,category_travel
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296670,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1296671,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1296672,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1296673,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1296674,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
data = pd.concat([data.drop("category", axis = 1), category_df], axis=1)

In [13]:
data

,trans_date_trans_time,merchant,amt,gender,city,state,zip,city_pop,job,dob,...,category_grocery_pos,category_health_fitness,category_home,category_kids_pets,category_misc_net,category_misc_pos,category_personal_care,category_shopping_net,category_shopping_pos,category_travel
0,2019-01-01 00:00:18,"fraud_Rippin, Kub and Mann",4.97,0,Moravian Falls,NC,28654,3495,"Psychologist, counselling",1988-03-09,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,2019-01-01 00:00:44,"fraud_Heller, Gutmann and Zieme",107.23,0,Orient,WA,99160,149,Special educational needs teacher,1978-06-21,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2019-01-01 00:00:51,fraud_Lind-Buckridge,220.11,1,Malad City,ID,83252,4154,Nature conservation officer,1962-01-19,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2019-01-01 00:01:16,"fraud_Kutch, Hermiston and Farrell",45.00,1,Boulder,MT,59632,1939,Patent attorney,1967-01-12,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2019-01-01 00:03:06,fraud_Keeling-Crist,41.96,1,Doe Hill,VA,24433,99,Dance movement psychotherapist,1986-03-28,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296670,2020-06-21 12:12:08,fraud_Reichel Inc,15.56,1,Hatch,UT,84735,258,Geoscientist,1961-11-24,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1296671,2020-06-21 12:12:19,fraud_Abernathy and Sons,51.70,1,Tuscarora,MD,21790,100,"Production assistant, television",1979-12-11,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1296672,2020-06-21 12:12:32,fraud_Stiedemann Ltd,105.93,1,High Rolls Mountain Park,NM,88325,899,Naval architect,1967-08-30,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1296673,2020-06-21 12:13:36,"fraud_Reinger, Weissnat and Strosin",74.90,1,Manderson,SD,57756,1126,Volunteer coordinator,1980-08-18,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1296674,2020-06-21 12:13:37,"fraud_Langosh, Wintheiser and Hyatt",4.30,1,Sula,MT,59871,218,"Therapist, horticultural",1995-08-16,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
data["trans_date_trans_time"] = pd.to_datetime(data["trans_date_trans_time"])

In [15]:
data['transaction_hour'] = data['trans_date_trans_time'].dt.hour
data['transaction_day'] = data['trans_date_trans_time'].dt.day
data['transaction_month'] = data['trans_date_trans_time'].dt.month
data['transaction_weekday'] = data['trans_date_trans_time'].dt.weekday

In [16]:
data.drop("trans_date_trans_time",axis = 1, inplace=True)

In [17]:
data

,merchant,amt,gender,city,state,zip,city_pop,job,dob,merch_lat,...,category_misc_net,category_misc_pos,category_personal_care,category_shopping_net,category_shopping_pos,category_travel,transaction_hour,transaction_day,transaction_month,transaction_weekday
0,"fraud_Rippin, Kub and Mann",4.97,0,Moravian Falls,NC,28654,3495,"Psychologist, counselling",1988-03-09,36.011293,...,1.0,0.0,0.0,0.0,0.0,0.0,0,1,1,1
1,"fraud_Heller, Gutmann and Zieme",107.23,0,Orient,WA,99160,149,Special educational needs teacher,1978-06-21,49.159047,...,0.0,0.0,0.0,0.0,0.0,0.0,0,1,1,1
2,fraud_Lind-Buckridge,220.11,1,Malad City,ID,83252,4154,Nature conservation officer,1962-01-19,43.150704,...,0.0,0.0,0.0,0.0,0.0,0.0,0,1,1,1
3,"fraud_Kutch, Hermiston and Farrell",45.00,1,Boulder,MT,59632,1939,Patent attorney,1967-01-12,47.034331,...,0.0,0.0,0.0,0.0,0.0,0.0,0,1,1,1
4,fraud_Keeling-Crist,41.96,1,Doe Hill,VA,24433,99,Dance movement psychotherapist,1986-03-28,38.674999,...,0.0,1.0,0.0,0.0,0.0,0.0,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296670,fraud_Reichel Inc,15.56,1,Hatch,UT,84735,258,Geoscientist,1961-11-24,36.841266,...,0.0,0.0,0.0,0.0,0.0,0.0,12,21,6,6
1296671,fraud_Abernathy and Sons,51.70,1,Tuscarora,MD,21790,100,"Production assistant, television",1979-12-11,38.906881,...,0.0,0.0,0.0,0.0,0.0,0.0,12,21,6,6
1296672,fraud_Stiedemann Ltd,105.93,1,High Rolls Mountain Park,NM,88325,899,Naval architect,1967-08-30,33.619513,...,0.0,0.0,0.0,0.0,0.0,0.0,12,21,6,6
1296673,"fraud_Reinger, Weissnat and Strosin",74.90,1,Manderson,SD,57756,1126,Volunteer coordinator,1980-08-18,42.788940,...,0.0,0.0,0.0,0.0,0.0,0.0,12,21,6,6
1296674,"fraud_Langosh, Wintheiser and Hyatt",4.30,1,Sula,MT,59871,218,"Therapist, horticultural",1995-08-16,46.565983,...,0.0,0.0,0.0,0.0,0.0,0.0,12,21,6,6

In [18]:
frequency = data['merchant'].value_counts()
data['merchant'] = data['merchant'].map(frequency)

In [19]:
data

,merchant,amt,gender,city,state,zip,city_pop,job,dob,merch_lat,...,category_misc_net,category_misc_pos,category_personal_care,category_shopping_net,category_shopping_pos,category_travel,transaction_hour,transaction_day,transaction_month,transaction_weekday
0,1267,4.97,0,Moravian Falls,NC,28654,3495,"Psychologist, counselling",1988-03-09,36.011293,...,1.0,0.0,0.0,0.0,0.0,0.0,0,1,1,1
1,2503,107.23,0,Orient,WA,99160,149,Special educational needs teacher,1978-06-21,49.159047,...,0.0,0.0,0.0,0.0,0.0,0.0,0,1,1,1
2,1895,220.11,1,Malad City,ID,83252,4154,Nature conservation officer,1962-01-19,43.150704,...,0.0,0.0,0.0,0.0,0.0,0.0,0,1,1,1
3,2613,45.00,1,Boulder,MT,59632,1939,Patent attorney,1967-01-12,47.034331,...,0.0,0.0,0.0,0.0,0.0,0.0,0,1,1,1
4,1592,41.96,1,Doe Hill,VA,24433,99,Dance movement psychotherapist,1986-03-28,38.674999,...,0.0,1.0,0.0,0.0,0.0,0.0,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296670,1907,15.56,1,Hatch,UT,84735,258,Geoscientist,1961-11-24,36.841266,...,0.0,0.0,0.0,0.0,0.0,0.0,12,21,6,6
1296671,1751,51.70,1,Tuscarora,MD,21790,100,"Production assistant, television",1979-12-11,38.906881,...,0.0,0.0,0.0,0.0,0.0,0.0,12,21,6,6
1296672,1853,105.93,1,High Rolls Mountain Park,NM,88325,899,Naval architect,1967-08-30,33.619513,...,0.0,0.0,0.0,0.0,0.0,0.0,12,21,6,6
1296673,1910,74.90,1,Manderson,SD,57756,1126,Volunteer coordinator,1980-08-18,42.788940,...,0.0,0.0,0.0,0.0,0.0,0.0,12,21,6,6
1296674,1788,4.30,1,Sula,MT,59871,218,"Therapist, horticultural",1995-08-16,46.565983,...,0.0,0.0,0.0,0.0,0.0,0.0,12,21,6,6

In [20]:
frequency = data['city'].value_counts()
data['city'] = data['city'].map(frequency)

In [22]:
data

,merchant,amt,gender,city,state,zip,city_pop,job,dob,merch_lat,...,category_misc_net,category_misc_pos,category_personal_care,category_shopping_net,category_shopping_pos,category_travel,transaction_hour,transaction_day,transaction_month,transaction_weekday
0,1267,4.97,0,2028,NC,28654,3495,"Psychologist, counselling",1988-03-09,36.011293,...,1.0,0.0,0.0,0.0,0.0,0.0,0,1,1,1
1,2503,107.23,0,3545,WA,99160,149,Special educational needs teacher,1978-06-21,49.159047,...,0.0,0.0,0.0,0.0,0.0,0.0,0,1,1,1
2,1895,220.11,1,503,ID,83252,4154,Nature conservation officer,1962-01-19,43.150704,...,0.0,0.0,0.0,0.0,0.0,0.0,0,1,1,1
3,2613,45.00,1,493,MT,59632,1939,Patent attorney,1967-01-12,47.034331,...,0.0,0.0,0.0,0.0,0.0,0.0,0,1,1,1
4,1592,41.96,1,2017,VA,24433,99,Dance movement psychotherapist,1986-03-28,38.674999,...,0.0,1.0,0.0,0.0,0.0,0.0,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296670,1907,15.56,1,1513,UT,84735,258,Geoscientist,1961-11-24,36.841266,...,0.0,0.0,0.0,0.0,0.0,0.0,12,21,6,6
1296671,1751,51.70,1,531,MD,21790,100,"Production assistant, television",1979-12-11,38.906881,...,0.0,0.0,0.0,0.0,0.0,0.0,12,21,6,6
1296672,1853,105.93,1,2070,NM,88325,899,Naval architect,1967-08-30,33.619513,...,0.0,0.0,0.0,0.0,0.0,0.0,12,21,6,6
1296673,1910,74.90,1,2024,SD,57756,1126,Volunteer coordinator,1980-08-18,42.788940,...,0.0,0.0,0.0,0.0,0.0,0.0,12,21,6,6
1296674,1788,4.30,1,1512,MT,59871,218,"Therapist, horticultural",1995-08-16,46.565983,...,0.0,0.0,0.0,0.0,0.0,0.0,12,21,6,6

In [23]:
frequency = data['state'].value_counts()
data['state'] = data['state'].map(frequency)

In [25]:
data.columns

Index(['merchant', 'amt', 'gender', 'city', 'state', 'zip', 'city_pop', 'job',
       'dob', 'merch_lat', 'merch_long', 'is_fraud', 'category_entertainment',
       'category_food_dining', 'category_gas_transport',
       'category_grocery_net', 'category_grocery_pos',
       'category_health_fitness', 'category_home', 'category_kids_pets',
       'category_misc_net', 'category_misc_pos', 'category_personal_care',
       'category_shopping_net', 'category_shopping_pos', 'category_travel',
       'transaction_hour', 'transaction_day', 'transaction_month',
       'transaction_weekday'],
      dtype='object')

In [26]:
data

,merchant,amt,gender,city,state,zip,city_pop,job,dob,merch_lat,...,category_misc_net,category_misc_pos,category_personal_care,category_shopping_net,category_shopping_pos,category_travel,transaction_hour,transaction_day,transaction_month,transaction_weekday
0,1267,4.97,0,2028,30266,28654,3495,"Psychologist, counselling",1988-03-09,36.011293,...,1.0,0.0,0.0,0.0,0.0,0.0,0,1,1,1
1,2503,107.23,0,3545,18924,99160,149,Special educational needs teacher,1978-06-21,49.159047,...,0.0,0.0,0.0,0.0,0.0,0.0,0,1,1,1
2,1895,220.11,1,503,5545,83252,4154,Nature conservation officer,1962-01-19,43.150704,...,0.0,0.0,0.0,0.0,0.0,0.0,0,1,1,1
3,2613,45.00,1,493,11754,59632,1939,Patent attorney,1967-01-12,47.034331,...,0.0,0.0,0.0,0.0,0.0,0.0,0,1,1,1
4,1592,41.96,1,2017,29250,24433,99,Dance movement psychotherapist,1986-03-28,38.674999,...,0.0,1.0,0.0,0.0,0.0,0.0,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296670,1907,15.56,1,1513,10699,84735,258,Geoscientist,1961-11-24,36.841266,...,0.0,0.0,0.0,0.0,0.0,0.0,12,21,6,6
1296671,1751,51.70,1,531,26193,21790,100,"Production assistant, television",1979-12-11,38.906881,...,0.0,0.0,0.0,0.0,0.0,0.0,12,21,6,6
1296672,1853,105.93,1,2070,16407,88325,899,Naval architect,1967-08-30,33.619513,...,0.0,0.0,0.0,0.0,0.0,0.0,12,21,6,6
1296673,1910,74.90,1,2024,12324,57756,1126,Volunteer coordinator,1980-08-18,42.788940,...,0.0,0.0,0.0,0.0,0.0,0.0,12,21,6,6
1296674,1788,4.30,1,1512,11754,59871,218,"Therapist, horticultural",1995-08-16,46.565983,...,0.0,0.0,0.0,0.0,0.0,0.0,12,21,6,6

In [27]:
data["dob"] = pd.to_datetime(data["dob"])

In [33]:
def calculate_age(birthdate):
    today = datetime.today()
    return today.year - birthdate.year - ((today.month, today.day) < (birthdate.month, birthdate.day))


data['age'] = data['dob'].apply(calculate_age)

In [36]:
data.drop("dob",axis = 1, inplace = True)

In [37]:
data

,merchant,amt,gender,city,state,zip,city_pop,job,merch_lat,merch_long,...,category_misc_pos,category_personal_care,category_shopping_net,category_shopping_pos,category_travel,transaction_hour,transaction_day,transaction_month,transaction_weekday,age
0,1267,4.97,0,2028,30266,28654,3495,"Psychologist, counselling",36.011293,-82.048315,...,0.0,0.0,0.0,0.0,0.0,0,1,1,1,36
1,2503,107.23,0,3545,18924,99160,149,Special educational needs teacher,49.159047,-118.186462,...,0.0,0.0,0.0,0.0,0.0,0,1,1,1,46
2,1895,220.11,1,503,5545,83252,4154,Nature conservation officer,43.150704,-112.154481,...,0.0,0.0,0.0,0.0,0.0,0,1,1,1,62
3,2613,45.00,1,493,11754,59632,1939,Patent attorney,47.034331,-112.561071,...,0.0,0.0,0.0,0.0,0.0,0,1,1,1,57
4,1592,41.96,1,2017,29250,24433,99,Dance movement psychotherapist,38.674999,-78.632459,...,1.0,0.0,0.0,0.0,0.0,0,1,1,1,38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296670,1907,15.56,1,1513,10699,84735,258,Geoscientist,36.841266,-111.690765,...,0.0,0.0,0.0,0.0,0.0,12,21,6,6,62
1296671,1751,51.70,1,531,26193,21790,100,"Production assistant, television",38.906881,-78.246528,...,0.0,0.0,0.0,0.0,0.0,12,21,6,6,44
1296672,1853,105.93,1,2070,16407,88325,899,Naval architect,33.619513,-105.130529,...,0.0,0.0,0.0,0.0,0.0,12,21,6,6,57
1296673,1910,74.90,1,2024,12324,57756,1126,Volunteer coordinator,42.788940,-103.241160,...,0.0,0.0,0.0,0.0,0.0,12,21,6,6,44
1296674,1788,4.30,1,1512,11754,59871,218,"Therapist, horticultural",46.565983,-114.186110,...,0.0,0.0,0.0,0.0,0.0,12,21,6,6,29

In [38]:
job_encoder = LabelEncoder()
data["job"] = job_encoder.fit_transform(data["job"])

In [39]:
data

,merchant,amt,gender,city,state,zip,city_pop,job,merch_lat,merch_long,...,category_misc_pos,category_personal_care,category_shopping_net,category_shopping_pos,category_travel,transaction_hour,transaction_day,transaction_month,transaction_weekday,age
0,1267,4.97,0,2028,30266,28654,3495,370,36.011293,-82.048315,...,0.0,0.0,0.0,0.0,0.0,0,1,1,1,36
1,2503,107.23,0,3545,18924,99160,149,428,49.159047,-118.186462,...,0.0,0.0,0.0,0.0,0.0,0,1,1,1,46
2,1895,220.11,1,503,5545,83252,4154,307,43.150704,-112.154481,...,0.0,0.0,0.0,0.0,0.0,0,1,1,1,62
3,2613,45.00,1,493,11754,59632,1939,328,47.034331,-112.561071,...,0.0,0.0,0.0,0.0,0.0,0,1,1,1,57
4,1592,41.96,1,2017,29250,24433,99,116,38.674999,-78.632459,...,1.0,0.0,0.0,0.0,0.0,0,1,1,1,38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296670,1907,15.56,1,1513,10699,84735,258,215,36.841266,-111.690765,...,0.0,0.0,0.0,0.0,0.0,12,21,6,6,62
1296671,1751,51.70,1,531,26193,21790,100,360,38.906881,-78.246528,...,0.0,0.0,0.0,0.0,0.0,12,21,6,6,44
1296672,1853,105.93,1,2070,16407,88325,899,308,33.619513,-105.130529,...,0.0,0.0,0.0,0.0,0.0,12,21,6,6,57
1296673,1910,74.90,1,2024,12324,57756,1126,485,42.788940,-103.241160,...,0.0,0.0,0.0,0.0,0.0,12,21,6,6,44
1296674,1788,4.30,1,1512,11754,59871,218,467,46.565983,-114.186110,...,0.0,0.0,0.0,0.0,0.0,12,21,6,6,29

In [47]:
len(data.columns)

30

In [52]:
input = data.iloc[:,[i for i in range(0,30) if i != 10]]

In [54]:
output = data.iloc[:,10]

In [55]:
output

0          0
1          0
2          0
3          0
4          0
          ..
1296670    0
1296671    0
1296672    0
1296673    0
1296674    0
Name: is_fraud, Length: 1296675, dtype: int64

In [56]:
tree_model = DecisionTreeClassifier()

In [57]:
tree_model.fit(input,output)

DecisionTreeClassifier()

In [59]:
regression_model = LogisticRegression()

In [60]:
regression_model.fit(input,output)

c:\Users\dumbr\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [80]:
data_test = pd.read_csv("fraudTest.csv")

In [81]:
data_test.columns

Index(['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category',
       'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip',
       'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time',
       'merch_lat', 'merch_long', 'is_fraud'],
      dtype='object')

In [82]:
data_test

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555714,555714,2020-12-31 23:59:07,30560609640617,fraud_Reilly and Sons,health_fitness,43.77,Michael,Olson,M,558 Michael Estates,...,40.4931,-91.8912,519,Town planner,1966-02-13,9b1f753c79894c9f4b71f04581835ada,1388534347,39.946837,-91.333331,0
555715,555715,2020-12-31 23:59:09,3556613125071656,fraud_Hoppe-Parisian,kids_pets,111.84,Jose,Vasquez,M,572 Davis Mountains,...,29.0393,-95.4401,28739,Futures trader,1999-12-27,2090647dac2c89a1d86c514c427f5b91,1388534349,29.661049,-96.186633,0
555716,555716,2020-12-31 23:59:15,6011724471098086,fraud_Rau-Robel,kids_pets,86.88,Ann,Lawson,F,144 Evans Islands Apt. 683,...,46.1966,-118.9017,3684,Musician,1981-11-29,6c5b7c8add471975aa0fec023b2e8408,1388534355,46.658340,-119.715054,0
555717,555717,2020-12-31 23:59:24,4079773899158,fraud_Breitenberg LLC,travel,7.99,Eric,Preston,M,7020 Doyle Stream Apt. 951,...,44.6255,-116.4493,129,Cartographer,1965-12-15,14392d723bb7737606b2700ac791b7aa,1388534364,44.470525,-117.080888,0
555718,555718,2020-12-31 23:59:34,4170689372027579,fraud_Dare-Marvin,entertainment,38.13,Samuel,Frey,M,830 Myers Plaza Apt. 384,...,35.6665,-97.4798,116001,Media buyer,1993-05-10,1765bb45b3aa3224b4cdcb6e7a96cee3,1388534374,36.210097,-97.036372,0

In [83]:

data_test = data_test.drop(["Unnamed: 0","trans_num","cc_num","first","last","street","lat","long","unix_time"],axis = 1)

encoder = LabelEncoder()
data_test["gender"] = encoder.fit_transform(data_test["gender"])

category_encoder = OneHotEncoder()
encoded_category = category_encoder.fit_transform(data_test[["category"]]).toarray()
category_names = category_encoder.get_feature_names_out()
category_df = pd.DataFrame(encoded_category, columns=category_names)

data_test = pd.concat([data_test.drop("category", axis = 1), category_df], axis=1)

data_test["trans_date_trans_time"] = pd.to_datetime(data_test["trans_date_trans_time"])
data_test['transaction_hour'] = data_test['trans_date_trans_time'].dt.hour
data_test['transaction_day'] = data_test['trans_date_trans_time'].dt.day
data_test['transaction_month'] = data_test['trans_date_trans_time'].dt.month
data_test['transaction_weekday'] = data_test['trans_date_trans_time'].dt.weekday 
data_test.drop("trans_date_trans_time",axis = 1, inplace=True)

frequency = data_test['merchant'].value_counts()
data_test['merchant'] = data_test['merchant'].map(frequency)


frequency = data_test['city'].value_counts()
data_test['city'] = data_test['city'].map(frequency)


frequency = data_test['state'].value_counts()
data_test['state'] = data_test['state'].map(frequency)


data_test["dob"] = pd.to_datetime(data_test["dob"])
def calculate_age(birthdate):
    today = datetime.today()
    return today.year - birthdate.year - ((today.month, today.day) < (birthdate.month, birthdate.day))


data_test['age'] = data_test['dob'].apply(calculate_age)

data_test.drop("dob",axis = 1, inplace = True)

job_encoder = LabelEncoder()
data_test["job"] = job_encoder.fit_transform(data_test["job"])

In [84]:
data_test

,merchant,amt,gender,city,state,zip,city_pop,job,merch_lat,merch_long,...,category_misc_pos,category_personal_care,category_shopping_net,category_shopping_pos,category_travel,transaction_hour,transaction_day,transaction_month,transaction_weekday,age
0,736,2.86,1,640,12541,29209,333497,275,33.986391,-81.200714,...,0.0,1.0,0.0,0.0,0.0,12,21,6,6,56
1,785,29.84,0,837,4658,84002,302,392,39.450498,-109.960431,...,0.0,1.0,0.0,0.0,0.0,12,21,6,6,34
2,755,41.28,0,1073,35918,11710,34496,259,40.495810,-74.196111,...,0.0,0.0,0.0,0.0,0.0,12,21,6,6,54
3,711,60.05,1,663,18104,32780,54767,407,28.812398,-80.883061,...,1.0,0.0,0.0,0.0,0.0,12,21,6,6,37
4,370,3.19,1,891,19671,49632,1126,196,44.959148,-85.884734,...,0.0,0.0,0.0,0.0,1.0,12,21,6,6,69
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555714,757,43.77,1,628,16501,63453,519,460,39.946837,-91.333331,...,0.0,0.0,0.0,0.0,0.0,23,31,12,3,58
555715,1006,111.84,1,1105,40393,77566,28739,198,29.661049,-96.186633,...,0.0,0.0,0.0,0.0,0.0,23,31,12,3,24
555716,1043,86.88,0,1672,8116,99323,3684,294,46.658340,-119.715054,...,0.0,0.0,0.0,0.0,0.0,23,31,12,3,42
555717,346,7.99,1,883,2490,83643,129,58,44.470525,-117.080888,...,0.0,0.0,0.0,0.0,1.0,23,31,12,3,58
555718,783,38.13,1,1090,11379,73034,116001,276,36.210097,-97.036372,...,0.0,0.0,0.0,0.0,0.0,23,31,12,3,31

In [85]:
test_input = data_test.iloc[:,[i for i in range(0,30) if i != 10]]

In [86]:
tree_predicted = tree_model.predict(test_input)

In [87]:
regression_predicted = regression_model.predict(test_input)